# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/osboxes/workspace/weather-app/ext/poco-1.9.0
POCO_BUILD = /home/osboxes/workspace/weather-app/ext/poco-1.9.0
POCO_FLAGS = 
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL MongoDB PDF CppParser
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
